org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64
android.useAndroidX=true
android.enableJetifier=true

# Permission handler settings for Android
PERMISSION_HANDLER_PERMISSION_ACTIVITY_RECOGNITION=true
PERMISSION_HANDLER_PERMISSION_SENSORS=true
